"""create ai_analyses table

Revision ID: 749004af92a7
Revises: 943402d57603
Create Date: 2026-09-10 08:43:52.590457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749004af92a7'
down_revision: Union[str, Sequence[str], None] = '943402d57603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('probability', sa.String(), nullable=False),
    sa.Column('impact', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
